pipeline {
    agent any
    stages {
        stage('Clone dependencies') {
            steps {
                dir('cpp/lib') {
                    sh 'git clone https://github.com/google/googletest.git'
                    sh 'git clone https://github.com/unittest-cpp/unittest-cpp.git'
                }
            }
        }
        stage('cmake && build') {
            steps {
                dir('cpp') {
                    sh 'cmake -S . -B build'
                    sh 'cmake --build build --target all'
                }
            }
        }
        stage('Run Boost.Test') {
            steps {
                dir('cpp/build/frameworks/boost.test') {
                    sh './Boost.Test --log_format=XML --log_sink=./Boost.Test.xml --log_level=all --report_level=no --result_code=no'
                }
            }
        }
        stage('Run Catch2') {
            steps {
                dir('cpp/build/frameworks/catch2') {
                    sh './Catch2Test -s -r junit -o Catch2Test.xml'
                }
            }
        }
        // stage('run googletest') {
        //     steps {
        //         sh './cpp/build/frameworks/googletest/GoogleTest --gtest_output=xml:./GoogleTest.xml'
        //         junit './cpp/build/frameworks/googletest/GoogleTest.xml'
        //     }
        // }
        // stage('run unittest++') {
        //     steps {
        //         sh './cpp/build/frameworks/unittest++/UnitTestPP'
        //     }
        // }
    }
    post {
        always{
            xunit (
                thresholds: [ skipped(failureThreshold: '0'), failed(failureThreshold: '2') ],
                tools: [
                    BoostTest(pattern: '**/build/frameworks/boost.test/Boost.Test.xml'),
                    JUnit(pattern: '**/build/frameworks/catch2/Catch2Test.xml')
                ]
            )
            cleanWs()
            sh 'rm -rf cpp/lib'
            sh 'rm -rf cpp/build'
        }
    }
}